os: linux
language: node_js
node_js:
  - 12
before_script:
  - npm install
script: npm run build
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: source
