os: linux
language: node_js
node_js:
  - 14
before_script:
  - npm install
before_install:
  - export TZ=America/Sao_Paulo
script: npm run build
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: source
