#Author
author:
  photo: /me.jpg
  bio:
    header: Olá!
    content: Meu nome é Max Naegeler Roecker. Sou Bacharel em Ciência da Computação, Técnico em Informática e mestrando em Ciência da Computação. Fascinado por computadores desde o primeira vista.
  intro:
    header: Entre em contato
    content: Além desse site, você pode me encontrar no [Twitter](https://twitter.com/maxrkr) ou no [Linkedin](https://www.linkedin.com/in/maxroecker). Sinta-se à vontade para [enviar-me um email](mailto:max.roecker@gmail.com) também.

#Site
site:
  license:
    url: https://creativecommons.org/licenses/by/4.0/legalcode
    text: 'Exceto esteja explicíto, todo o conteúdo desse site está licenciado sob [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/) e os códigos estão sob [Domínio Publico](http://unlicense.org/).'
  logo: /logo.svg
  menu:
    Blog: /blog/
    Sobre: /about/
    Now: /now/

twitter:
  site: '@maxrkr'
  creator: '@maxrkr'

facebook:
  profile: 'https://www.facebook.com/MaxNRoecker'

googleAnalytics:
  id: 'UA-75618595-1'
